# Pydantic schemas for data validation and API request/response models

from pydantic import BaseModel
from datetime import date
from typing import Optional

class ApplicationBase(BaseModel):
    """
    Base schema with common fields for application data.
    Used as a foundation for other application schemas.
    """
    company: str
    role: str
    application_date: date
    deadline_date: Optional[date] = None
    status: str
    notes: Optional[str] = None

class ApplicationCreate(ApplicationBase):
    """
    Schema for creating new applications.
    Inherits all fields from ApplicationBase (no additional fields needed).
    """
    pass

class ApplicationUpdate(BaseModel):
    """
    Schema for updating existing applications.
    All fields are optional since updates can be partial.
    """
    company: Optional[str] = None
    role: Optional[str] = None
    application_date: Optional[date] = None
    deadline_date: Optional[date] = None
    status: Optional[str] = None
    notes: Optional[str] = None

class ApplicationResponse(BaseModel):
    """
    Schema for API responses containing application data.
    Includes the ID field which is generated by the database.
    """
    id: int
    company: str
    role: str
    application_date: date
    deadline_date: Optional[date] = None
    status: str
    notes: Optional[str] = None

    class Config:
        # Enable ORM mode to work with SQLAlchemy models
        from_attributes = True